import './globals.css'
import { Montserrat } from 'next/font/google'

const montserrat = Montserrat({ 
  weight: ['400','700'],
  subsets: ['latin'],
  variable: '--font-montserrat',
})

export const metadata = {
  title: 'Movies',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head/>

      <body className='${montserrat.className} bg-black min-h-screen text-white px-24 py-12'>
        {children}     
      </body>
    </html>
  )
}
